spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/companies-qa
    username: debuggeandoideas-qa
    password: udemy123456
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
