spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/companies
    username: debuggeandoideas-prod
    password: udemy1234
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
